# 
theme                    : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "neon" #"sunrise" , "default" , "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum"

# Site settings
locale                   : "en-US"
title                    : "Buffmire Blog"
title_separator          : "|"
subtitle                 : Stories of doing.
name                     : "Jameson Buffmire"
description              : "I do stuff and occasionally I write."
url                      : "blog.buffmire.com"
baseurl                  : "/blog"
repository               : "jtbuffmire/buffmire-blog"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
twitter_username         : jtbuffmire
github_username          : jtbuffmire

# breadcrumbs            : false # true, false (default)
words_per_minute         : 200


# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
